server:
  port: 8090
spring:
  application:
    name: cart-service
  redis:
    host: 127.0.0.1
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  jwt:
    pubKeyPath: /Users/bystander/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称