server:
  port: 8084
spring:
  application:
    name: page-service
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZont: http://127.0.0.1:10086/eureka
